print("saisir le jour :")
jour=input()
print("saisir les heures :")
heure=input()
print("saisir les minutes :")
minutes=input()
jour=int(jour)
heure=int(heure)
minutes=int(minutes)
nb=(jour*24*60+heure*60+minutes)
print(nb)
